[workspace]
authors = ["Markus Weber <markus.weberino@gmail.com>"]
channels = ["conda-forge"]
name = "talewind"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
format = "ruff check --select I --fix && ruff format"
lint = "ruff check"
lemonfox = "python src/examples/lemonfox.py"
talewind_app = "python src/talewind_app.py"


[dependencies]
python = "3.12.*"
ruff = ">=0.11.7,<0.12"
portaudio = ">=19.7.0,<20"
pyaudio = ">=0.2.14,<0.3"

[pypi-dependencies]
openai = { version = "*", extras = ["voice-helpers"] }
# talewind = { path = "./src/talewind", editable = true }