[workspace]
authors = ["Markus Weber <markus.weberino@gmail.com>"]
channels = ["conda-forge"]
name = "talewind"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
format = "ruff check --select I --fix && ruff format"
lint = "ruff check"

[dependencies]
python = "3.9.*"
ruff = ">=0.11.7,<0.12"

[pypi-dependencies]
myshell-openvoice = { git = "https://github.com/myshell-ai/OpenVoice.git" }
melotts = { git = "https://github.com/myshell-ai/MeloTTS.git" }
