[workspace]
authors = ["Markus Weber <markus.weberino@gmail.com>"]
channels = ["conda-forge"]
name = "talewind"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
format = "ruff check --select I --fix && ruff format"
lint = "ruff check"
setup = ". ./commands/tts.sh"
tts = "python src/examples/openvoice_example.py"

[dependencies]
python = "3.9.*"
ruff = ">=0.11.7,<0.12"
ffmpeg = ">=7.1.1,<8"
nltk = ">=3.9.1,<4"
setuptools = ">=65.0.0,<66"


[pypi-dependencies]
myshell-openvoice = { git = "https://github.com/myshell-ai/OpenVoice.git" }
melotts = { git = "https://github.com/myshell-ai/MeloTTS.git" }
