FROM ubuntu:24.04
LABEL maintainer="@fellfalla"

# Non-interactive installs
ENV DEBIAN_FRONTEND=noninteractive

# Install development essentials
RUN apt-get update && \
    apt-get install -y sudo git curl nano && \
    rm -rf /var/lib/apt/lists/*

##### Setup User Environment #####
# Create group and user matching host IDs

# Configure build-time arguments for mapping host UID/GID
ARG USER_UID=1000
ARG USER_GID=1000
ARG USERNAME=devuser

RUN echo "USER_UID=${USER_UID}"
RUN echo "USER_GID=${USER_GID}"

RUN groupadd --gid ${USER_GID} ${USERNAME} && \
    useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

# Set working directory
WORKDIR /workspace

# Create zsh cli
RUN apt-get update && \
    apt-get install -y zsh && \
    rm -rf /var/lib/apt/lists/*


VOLUME ["/dc/shellhistory"]
RUN mkdir -p /dc/shellhistory && \
    chown -R ${USERNAME}:${USERNAME} /dc/shellhistory

VOLUME ["/home/${USERNAME}/.vscode-server"]
RUN mkdir -p /home/${USERNAME}/.vscode-server && \
    chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.vscode-server && \
    chmod -R 777 /home/${USERNAME}/.vscode-server
    

# Switch to non-root user
USER ${USERNAME}

# Uses "git", "ssh-agent" and "history-substring-search" bundled plugins
RUN curl -L https://github.com/deluan/zsh-in-docker/releases/download/v1.2.1/zsh-in-docker.sh | \
    sh -s -- \
    -t agnoster \
    -p history-substring-search \
    -p history \
    -p git \
    -p ssh-agent \
    -p zsh-autosuggestions \
    -a 'export HISTFILE=/dc/shellhistory/.zsh_history' \
    -a 'export HISTSIZE=10000' \
    -a 'export SAVEHIST=10000' \
    -a 'setopt appendhistory' && \
    git clone --branch v0.7.1 https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Set the default shell to zsh
ENV SHELL=/bin/zsh
