FROM ubuntu:24.04
LABEL maintainer="@fellfalla"

# Non-interactive installs
ENV DEBIAN_FRONTEND=noninteractive

# Install development essentials
RUN apt-get update && \
    apt-get install -y sudo git curl nano && \
    rm -rf /var/lib/apt/lists/*

##### Setup User Environment #####
# Create group and user matching host IDs

# Configure build-time arguments for mapping host UID/GID
ARG USER_UID=1000
ARG USER_GID=1000
RUN echo "USER_UID=${USER_UID}"
RUN echo "USER_GID=${USER_GID}"

RUN groupadd --gid ${USER_GID} devuser && \
    useradd --uid ${USER_UID} --gid ${USER_GID} -m devuser && \
    echo "devuser ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/devuser && \
    chmod 0440 /etc/sudoers.d/devuser

# Set working directory
WORKDIR /workspace

# Create zsh cli
RUN apt-get update && \
    apt-get install -y zsh && \
    rm -rf /var/lib/apt/lists/*

# Switch to non-root user
USER devuser

# Uses "git", "ssh-agent" and "history-substring-search" bundled plugins
RUN curl -L https://github.com/deluan/zsh-in-docker/releases/download/v1.2.1/zsh-in-docker.sh | \
    sh -s -- \
    -t agnoster \
    -p history-substring-search \
    -p history \
    -p git \
    -p ssh-agent \
    -a 'export HISTFILE=/dc/shellhistory/.zsh_history' \
    -a 'export HISTSIZE=10000' \
    -a 'export SAVEHIST=10000' \
    -a 'setopt appendhistory' \
    -a 'fpath+=(/usr/share/zsh/site-functions)' \
    -a 'zstyle ":completion:*" use-cache on' \
    -a 'zstyle ":completion:*" cache-path ~/.zsh/cache' \
    -a 'autoload -U compinit && compinit'



VOLUME ["/dc/shellhistory"]


# Set the default shell to zsh
ENV SHELL=/bin/zsh
